# 1. ETAPA DE CONSTRUCCIÓN: Utilizada para instalar dependencias
FROM node:20-alpine AS builder

WORKDIR /app
COPY src/package*.json ./
RUN npm install
COPY src/ .

# 2. ETAPA DE PRODUCCIÓN: Imagen final, más pequeña y segura
FROM node:20-alpine AS final

# Configuración: Establece el puerto, el usuario y el directorio
WORKDIR /usr/src/app
ENV NODE_ENV production
EXPOSE 3000

# Copia los artefactos de la etapa 'builder'
COPY --from=builder /app .

# Comando principal para iniciar la aplicación
CMD ["npm", "start"]